### ISSUE TITLE
Bug: 429エラーの多発

### ISSUE THREAD

**Issue by Geusen** [m1daily/Schedule_Bot#16]
### 0.ラベル付け

- [X] ①ステータス  状態を表すラベル(Issue作成時は待機中で良い)
- [X] ②タイプ  作業の種別を表すラベル
- [X] ③優先度  優先度を表すラベル(任意)
- [X] ④作業量  想定される作業量を表すラベル(任意)

### 1.概要

Imgurでエラー

### 2.再現手順、エラー内容等

- https://github.com/m1daily/Schedule_Bot/actions/runs/4112528846
   - 217行目～

### エラーコード(任意)

```
▶pip install --upgrade pip
(中略)


Traceback (most recent call last):

  File "/home/runner/work/Schedule_Bot/Schedule_Bot/schedule.py", line 133, in <module>
[2023年02月07日(火) 18:43:41]
    img_url = imgur(img_url, 'url')
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/Schedule_Bot/Schedule_Bot/schedule.py", line 78, in imgur
    r.raise_for_status()
  File "/opt/hostedtoolcache/Python/3.11.1/x64/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.imgur.com/3/upload
[抽出画像]
1枚目: https://lh4.googleusercontent.com/jzoFVCVe7RHu2BuPllMiUSHM8OlEOual_q-1cRLM35KaNmK_dM7sgYiskYP_bfXV9z8GzPsJZ_Y3YcndOsvpjVW-j7hOiS2cYQWz5BsuN_QbAfh6i01iJ0qzqS7WEBhub1UgfoJrGqWY8oxM?alr=yes
Error: Process completed with exit code 1.
```

### 3.関連Issue、Discussions(任意)

特になし

### 4.原因(任意)

- Imgurのエラー(429 Too Many Requests)

[参考](https://teratail.com/questions/fuux347lsxre3o)
> ① １ユーザーあたり一日当たりのリクエスト上限：およそ12,500回
> ② １ユーザーあたり一日当たりのアップロード上限：およそ1,250回
> ③ 同一月に①または②の上限を超える日が５回発生した場合、その日以降から月末まで制限される。
> ④ （APIキーだけではなく）IPアドレスも識別して制限（別ユーザーでも、テザリングの使用やBBルーター等でIPアドレスが同じになることはありえます）

### 5.修正案(任意)

~~- [x] sleep追加~~
~~- [ ] 別アカウントでトークン発行~~
[x] url.request削除

**Comment by Geusen** [comment]
様子見

**Comment by Geusen** [comment]
`files = {'image' : requests.get(image).content}`が原因である可能性がある為、画像をDLしてからアップロードする形に変更

**Comment by Geusen** [comment]
画像urlでリクエストすると駄目だったっぽい
画像ファイルからリクエストすればセーフ
